export type AuthorityType = "national" | "state" | "local" | "supranational";
export type SourceKind = "webpage" | "rss" | "news_search";
export type ReliabilityTier = 1 | 2 | 3 | 4 | 5;

export interface SourceRecord {
  id: string;
  name: string;
  url: string;
  authorityType: AuthorityType;
  jurisdiction: string;
  region: string;
  reliabilityTier: ReliabilityTier;
  kind: SourceKind;
  notes?: string;
}

export const sourceRegistry: SourceRecord[] = [
  {
    id: "us-federal-register-rss",
    name: "Federal Register",
    url: "https://www.federalregister.gov/documents/search.rss?conditions%5Bterm%5D=child+digital+platforms+social+media",
    authorityType: "national",
    jurisdiction: "United States",
    region: "US",
    reliabilityTier: 5,
    kind: "rss",
    notes: "official US federal publication feed",
  },
  {
    id: "us-ftc-press-releases-rss",
    name: "FTC Press Releases",
    url: "https://www.ftc.gov/news-events/news/press-releases/rss",
    authorityType: "national",
    jurisdiction: "United States",
    region: "US",
    reliabilityTier: 5,
    kind: "rss",
    notes: "federal consumer and privacy updates",
  },
  {
    id: "us-fcc-news-rss",
    name: "FCC News Releases",
    url: "https://www.fcc.gov/news-events/news/rss.xml",
    authorityType: "national",
    jurisdiction: "United States",
    region: "US",
    reliabilityTier: 5,
    kind: "rss",
    notes: "communications and platform safety rulemaking",
  },
  {
    id: "us-ftc-children-search",
    name: "FTC Online Safety Search",
    url: "https://news.google.com/rss/search?q=site:ftc.gov%20child%20online%20privacy%20social%20media",
    authorityType: "national",
    jurisdiction: "United States",
    region: "US",
    reliabilityTier: 3,
    kind: "news_search",
    notes: "latest US federal safety-related news mentions",
  },
  {
    id: "us-ca-state-bill-search",
    name: "California Legislature Bill Updates",
    url: "https://news.google.com/rss/search?q=site:leginfo.legislature.ca.gov%20teen%20social%20media%20safety",
    authorityType: "state",
    jurisdiction: "California",
    region: "US-States",
    reliabilityTier: 4,
    kind: "news_search",
    notes: "state legislative activity affecting minors",
  },
  {
    id: "us-ca-cppa-search",
    name: "California Privacy Authority",
    url: "https://news.google.com/rss/search?q=site:cppa.ca.gov%20Age%20Appropriate%20Design%20Code",
    authorityType: "state",
    jurisdiction: "California",
    region: "US-States",
    reliabilityTier: 5,
    kind: "news_search",
    notes: "state regulator announcements for minor safety",
  },
  {
    id: "us-ny-district-rss",
    name: "New York State Senate",
    url: "https://www.nysenate.gov/legislation/search?search_api_views_fulltext=teens+social+media+age+verification",
    authorityType: "state",
    jurisdiction: "New York",
    region: "US-States",
    reliabilityTier: 4,
    kind: "webpage",
    notes: "state-level bill discussions and consultations",
  },
  {
    id: "us-tx-adv-rss",
    name: "Texas Attorney General",
    url: "https://www.txattorneygeneral.gov/newsroom/news?search=minor+social+media",
    authorityType: "state",
    jurisdiction: "Texas",
    region: "US-States",
    reliabilityTier: 5,
    kind: "webpage",
    notes: "state enforcement actions and consultations",
  },
  {
    id: "us-fl-child-online-search",
    name: "Florida Senate Privacy Search",
    url: "https://news.google.com/rss/search?q=site:flsenate.gov%20social%20media%20children%20privacy",
    authorityType: "state",
    jurisdiction: "Florida",
    region: "US-States",
    reliabilityTier: 3,
    kind: "news_search",
    notes: "state-level legislative filings",
  },
  {
    id: "eu-dsa-oj",
    name: "European Parliament",
    url: "https://www.europarl.europa.eu/rss/en.xml",
    authorityType: "supranational",
    jurisdiction: "European Union",
    region: "EU",
    reliabilityTier: 5,
    kind: "rss",
    notes: "supranational policy updates and digital regulation",
  },
  {
    id: "eu-ec-digital-rss",
    name: "European Commission Digital",
    url: "https://digital-strategy.ec.europa.eu/en/rss.xml",
    authorityType: "supranational",
    jurisdiction: "European Union",
    region: "EU",
    reliabilityTier: 5,
    kind: "rss",
    notes: "official digital policy posts",
  },
  {
    id: "eu-edpb-news",
    name: "European Data Protection Board",
    url: "https://edpb.europa.eu/our-work/newsroom/newsroom_en.rdf",
    authorityType: "supranational",
    jurisdiction: "European Union",
    region: "EU",
    reliabilityTier: 4,
    kind: "rss",
    notes: "privacy and child-related guidance",
  },
  {
    id: "eu-eu-commission-search",
    name: "EU DSA Child Online Search",
    url: "https://news.google.com/rss/search?q=site:ec.europa.eu%20digital%20services%20act%20children",
    authorityType: "supranational",
    jurisdiction: "European Union",
    region: "EU",
    reliabilityTier: 3,
    kind: "news_search",
    notes: "European legal developments tracked via news index",
  },
  {
    id: "uk-ico-rss",
    name: "UK ICO News",
    url: "https://ico.org.uk/media/about-the-ico/rss/feeds/news.rss",
    authorityType: "national",
    jurisdiction: "United Kingdom",
    region: "UK",
    reliabilityTier: 5,
    kind: "rss",
    notes: "UK regulator updates and press releases",
  },
  {
    id: "uk-ofcom-rss",
    name: "Ofcom Press Releases",
    url: "https://www.ofcom.org.uk/about-ofcom/corporate-statements-and-responses/press-releases/press-releases?output=1&destination=/feed/",
    authorityType: "national",
    jurisdiction: "United Kingdom",
    region: "UK",
    reliabilityTier: 4,
    kind: "rss",
    notes: "broadcast and online safety updates",
  },
  {
    id: "uk-hm-government-search",
    name: "UK Parliament Digital Search",
    url: "https://news.google.com/rss/search?q=site:parliament.uk%20online%20safety%20children%20social%20media",
    authorityType: "national",
    jurisdiction: "United Kingdom",
    region: "UK",
    reliabilityTier: 3,
    kind: "news_search",
    notes: "state policy discussion stream",
  },
  {
    id: "au-esafety-news",
    name: "eSafety Commissioner",
    url: "https://www.esafety.gov.au/news/rss",
    authorityType: "national",
    jurisdiction: "Australia",
    region: "APAC",
    reliabilityTier: 5,
    kind: "rss",
    notes: "official enforcement and safety updates",
  },
  {
    id: "au-accc-news",
    name: "ACCC Media",
    url: "https://www.accc.gov.au/media/media-releases/feed",
    authorityType: "national",
    jurisdiction: "Australia",
    region: "APAC",
    reliabilityTier: 5,
    kind: "rss",
    notes: "competition and consumer safety filings",
  },
  {
    id: "au-oaii-rss",
    name: "ACMA Media Release",
    url: "https://www.acma.gov.au/about-us/media-releases/rss",
    authorityType: "national",
    jurisdiction: "Australia",
    region: "APAC",
    reliabilityTier: 4,
    kind: "rss",
    notes: "communications regulator updates",
  },
  {
    id: "au-oaic-search",
    name: "Office of Australian Information Commissioner",
    url: "https://news.google.com/rss/search?q=site:oaic.gov.au%20children%20personal%20information%20social%20media",
    authorityType: "national",
    jurisdiction: "Australia",
    region: "APAC",
    reliabilityTier: 4,
    kind: "news_search",
    notes: "privacy commissioner updates in Australian context",
  },
  {
    id: "ca-crtc-rss",
    name: "CRTC Regulatory Decisions",
    url: "https://www.crtc.gc.ca/eng/com/reports/reports.htm#rss",
    authorityType: "national",
    jurisdiction: "Canada",
    region: "Canada",
    reliabilityTier: 5,
    kind: "webpage",
    notes: "Canadian communications regulation tracker",
  },
  {
    id: "ca-pc-news",
    name: "Privacy Commissioner Canada",
    url: "https://www.priv.gc.ca/en/news-and-events/newsroom/news-releases/?output=RSS",
    authorityType: "national",
    jurisdiction: "Canada",
    region: "Canada",
    reliabilityTier: 5,
    kind: "rss",
    notes: "official privacy office releases",
  },
  {
    id: "ca-justice-news-search",
    name: "Public Safety Canada Search",
    url: "https://news.google.com/rss/search?q=site:public-safety.canada.ca%20online%20safety%20children",
    authorityType: "national",
    jurisdiction: "Canada",
    region: "Canada",
    reliabilityTier: 3,
    kind: "news_search",
    notes: "policy tracking across Canada",
  },
  {
    id: "sg-pdpc-rss",
    name: "Singapore PDPC Announcements",
    url: "https://www.pdpc.gov.sg/en/announcements/rss",
    authorityType: "national",
    jurisdiction: "Singapore",
    region: "APAC",
    reliabilityTier: 5,
    kind: "rss",
    notes: "data protection announcements for minors",
  },
  {
    id: "sg-gov-search",
    name: "Singapore Government Gazette Search",
    url: "https://news.google.com/rss/search?q=site:egazette.gov.sg%20online%20regulation%20children",
    authorityType: "national",
    jurisdiction: "Singapore",
    region: "APAC",
    reliabilityTier: 4,
    kind: "news_search",
    notes: "official statutory update coverage",
  },
  {
    id: "india-meity-search",
    name: "India MeitY Safety Search",
    url: "https://news.google.com/rss/search?q=site:meity.gov.in%20child%20online%20safety%20social%20media",
    authorityType: "national",
    jurisdiction: "India",
    region: "APAC",
    reliabilityTier: 4,
    kind: "news_search",
    notes: "India technology policy signal stream",
  },
  {
    id: "japan-meti-rss",
    name: "Japanese METI Press",
    url: "https://www.meti.go.jp/press/rss/index.xml",
    authorityType: "national",
    jurisdiction: "Japan",
    region: "APAC",
    reliabilityTier: 5,
    kind: "rss",
    notes: "technology policy and platform notices",
  },
  {
    id: "korea-kisa-search",
    name: "KISA Digital Security Search",
    url: "https://news.google.com/rss/search?q=site:kisa.or.kr%20online%20children%20platform",
    authorityType: "national",
    jurisdiction: "South Korea",
    region: "APAC",
    reliabilityTier: 4,
    kind: "news_search",
    notes: "Korean cyber safety and platform safety updates",
  },
  {
    id: "br-latam-search",
    name: "Brazil Senado Search",
    url: "https://news.google.com/rss/search?q=site:senado.leg.br%20protecao%20dados%20crian%C3%A7a%20internet",
    authorityType: "national",
    jurisdiction: "Brazil",
    region: "LATAM",
    reliabilityTier: 4,
    kind: "news_search",
    notes: "Latin American child-data legislation tracking",
  },
  {
    id: "mx-cna-latam-search",
    name: "Mexico COFECE Search",
    url: "https://news.google.com/rss/search?q=site:cofece.mx%20redes%20sociales%20ni%C3%B1os",
    authorityType: "national",
    jurisdiction: "Mexico",
    region: "LATAM",
    reliabilityTier: 4,
    kind: "news_search",
    notes: "anti-competition and digital platform updates",
  },
];
